#!/bin/bash -e

usage() {
  echo "usage: $0"
  echo
  echo "Required Variables:"
  echo
  echo "  DOMAIN"
  echo "  DB_USER                Openbalena DB username"
  echo "  DB_PASSWORD            Openbalena DB password"
  echo "  DB_PORT                Openbalena DB port"
  echo "  HOST_MODE              Open-balena-admin host mode"
  echo "  VERSION                Openbalena API version tag"
  echo "  JWT_SECRET             Openbalena JWT secret"
  echo
}

for var in DOMAIN DB_USER DB_PASSWORD DB_PORT HOST_MODE VERSION JWT_SECRET; do
  if [ -z "${!var-}" ]; then
    usage
    exit 1
  fi
done

cat <<STR
export OPENBALENA_HOST_NAME=$DOMAIN
export OPENBALENA_DB_USER=$DB_USER
export OPENBALENA_DB_PASSWORD=$DB_PASSWORD
export OPENBALENA_DB_PORT=$DB_PORT
export OPENBALENA_ADMIN_HOST_MODE=$HOST_MODE
export OPENBALENA_API_VERSION_TAG=$VERSION
export OPENBALENA_JWT_SECRET=$JWT_SECRET
STR
